"""add_steps_to_recipes

Revision ID: 79d98145a5c0
Revises: bf7c9a2e1d30
Create Date: 2026-03-07 19:34:59.503716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79d98145a5c0'
down_revision: Union[str, Sequence[str], None] = 'bf7c9a2e1d30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ingredients_name_key'), 'ingredients', type_='unique')
    op.drop_index(op.f('ix_ingredients_name'), table_name='ingredients')
    op.create_index(op.f('ix_ingredients_name'), 'ingredients', ['name'], unique=True)
    op.add_column('recipes', sa.Column('steps', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'steps')
    op.drop_index(op.f('ix_ingredients_name'), table_name='ingredients')
    op.create_index(op.f('ix_ingredients_name'), 'ingredients', ['name'], unique=False)
    op.create_unique_constraint(op.f('ingredients_name_key'), 'ingredients', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
